delta10/signalen-frontend-wcag

src/app/layout.tsx

This change sets a better default title.

Set better default title

---

package.json
src/tests/address.test.ts
vitest.config.ts

This integrates vitest and react/testing library into our code, currently I only wrote a small test (expecting that 1 + 2 is 3) but in the near future we can use this testing library implementation to write more complex tests for api calls and more.

Feat: react/testing library and vitest setup

---

src/app/[locale]/incident/summary/components/IncidentSummaryForm.tsx

Feat: show step 2 answers in summary

---

src/app/[locale]/incident/contact/components/IncidentContactForm.tsx

Currently we show an incorrect label

Fix phone label

---

src/app/[locale]/components/FormProgress.tsx
src/app/[locale]/incident/add/components/AdditionalInformationPage.tsx
src/app/[locale]/incident/components/IncidentDescriptionPage.tsx
src/app/[locale]/incident/contact/components/IncidentContactPage.tsx
src/app/[locale]/incident/layout.tsx
src/app/[locale]/incident/summary/components/IncidentSummaryPage.tsx

feat: refactor form progress #137

---

src/app/[locale]/incident/components/IncidentFormFooter.tsx

Remove de left over "go" button uit PR #156

fix: remove "go" button

---

src/app/[locale]/incident/add/components/AdditionalInformationPage.tsx
src/app/[locale]/incident/add/components/IncidentQuestionsLocationForm.tsx
src/app/[locale]/incident/components/IncidentDescriptionForm.tsx
src/app/[locale]/incident/contact/components/IncidentContactForm.tsx
src/app/[locale]/incident/contact/components/IncidentContactPage.tsx
src/app/[locale]/incident/summary/components/IncidentSummaryForm.tsx
src/app/[locale]/incident/summary/components/IncidentSummaryPage.tsx
src/app/[locale]/page.tsx
src/lib/utils/stepper.ts
src/routing/navigation.ts
src/store/form_store.ts
src/types/form.ts
src/types/stores.ts

Feat: disable navigation to unfilled steps

---

src/app/[locale]/components/Header.tsx

fix: give priority to loading Logo

---

src/app/[locale]/incident/add/components/MapDialog.tsx
src/app/globals.css
src/components/index.ts
src/components/ui/upload/PreviewFile.tsx
translations/en.json
translations/nl.json

Hoort bij Issue #139 
**In deze PR**:
**`PreviewFile.tsx`**
* `<IconButton>` component implementeren en label toevoegen
* label toevoegen aan translation json files (NL/EN)
* refactoring: ongebruikte code verwijderen
* styling toevoegen `globals.css`
* todo's toevoegen `globals.css`
**`MapDialog.tsx`**
* `<IconButton>` component implementeren en label toevoegen 
* label toevoegen aan translation json files (NL/EN)
* classnames aanpassen
* refactor: ongebruikte code verwijderen
* moet nog gedaan worden: styling ongebruikte classes uit `globals.css` verwijderen (is nu alleen uitgecomment)

Feat/ IconButton implementeren (previewfile & mapdialog)

---

src/app/[locale]/incident/add/components/MapDialog.tsx

Fixes #180.
Is dit beter @bartjkdp ?

Fix: dramatic fly speed

---

src/app/[locale]/incident/add/components/MapDialog.tsx
src/app/[locale]/incident/add/components/questions/AssetSelect.tsx
src/app/[locale]/incident/add/components/questions/LocationSelect.tsx
translations/en.json
translations/nl.json

Fix: changed hardcoded text with intl language properties

---

src/app/[locale]/incident/contact/components/IncidentContactForm.tsx

Fix: removed unneccessary checkbox spacing and background color

---

src/app/[locale]/incident/add/components/questions/AssetSelect.tsx
src/app/[locale]/incident/add/components/questions/LocationSelect.tsx
src/app/[locale]/incident/summary/components/IncidentSummaryForm.tsx
src/components/ui/LocationMap.tsx

a11y: Consistency for dialog "edit" and "choose" button, decorative map unfocusable

---

src/app/[locale]/incident/components/IncidentFormFooter.tsx

Fixes #236 
- Back link in footer consistent with back link in progress bar

a11y: back link in footer consistent with back link in progress bar

---

src/app/[locale]/components/LanguageSwitch.tsx
src/app/[locale]/incident/add/components/MapDialog.tsx
src/app/globals.css

De locatie dialog in stap 2 heeft nu een donkere achtergrond in dark mode.

refactor: reduce tailwind class names

---

package-lock.json
package.json
src/app/[locale]/components/Footer.tsx
src/app/[locale]/incident/add/components/MapDialog.tsx
src/app/globals.css
src/components/index.ts
src/components/ui/LinkList.tsx
src/components/ui/LocationMap.tsx
src/components/ui/NextLinkWrapper.tsx

Various small improvements regarding focus styling. Refactored the footer to use the Link List from Utrecht but with a NextLinkWrapper, so the links aren't 100% wide anymore.

style: improve focus styles

---

src/app/[locale]/incident/add/components/questions/MapExplainerAccordion.tsx
src/app/globals.css

fix: contrast issues accordion light and darkmode

---

src/app/[locale]/incident/add/components/questions/MapExplainerAccordion.tsx

feat: add accordion scroll

---

.gitignore
README.md
package-lock.json
package.json
playwright.config.ts
test/e2e/step1.spec.ts
vitest.config.ts

Probeer het uit door:
```sh
npm run test-e2e
npx playwright show-report tmp/playwright-html-report
```

test: add Playwright for end-to-end tests

---

src/app/[locale]/incident/add/components/IncidentQuestionsLocationForm.tsx
src/app/[locale]/incident/add/components/questions/RenderSingleField.tsx
src/app/[locale]/incident/components/IncidentFormFooter.tsx

fix: dynamic form hard stop

---

translations/en.json
translations/nl.json

feat: change 'Nieuwe melding' to 'Maak nog een melding'

---

src/app/[locale]/incident/add/components/MapDialog.tsx

De knoppen om in te zoom en uit te zoomen werkten niet (meer?).
Hiermee wordt dit opgelost :)

fix: MapDialog zoom in and zoom out

---

src/app/[locale]/incident/add/components/MapDialog.tsx

https://github.com/tailwindlabs/headlessui/discussions/666\#discussioncomment-7489473

fix: add headlessui-portal-root so combobox in dialog works

---

src/app/[locale]/incident/add/components/AdditionalInformationPage.tsx
src/app/[locale]/incident/components/IncidentDescriptionPage.tsx
src/app/[locale]/incident/contact/components/IncidentContactPage.tsx
src/app/[locale]/incident/summary/components/IncidentSummaryPage.tsx
src/app/[locale]/incident/thankyou/components/ThankyouContent.tsx

fix: add `main` landmark

---

src/app/[locale]/incident/components/IncidentDescriptionForm.tsx
src/hooks/useDebounce.ts

Dit is het probleem dat @Yolijn eerder eens had gemeld. Ik kreeg het ook soms op een "vers" formulier. Nu eindelijk opgelost :)
Closes #404

Opgelost: Formulier gaat soms niet naar stap 2 
